### ISSUE TITLE
关于实验结果的请教

### ISSUE THREAD

**Issue by hzf-hhh** [xmu-xiaoma666/MFM#1]
作者，你好，我尝试将改进的强化学习添加到我的模型中，但是发现虽然cider指标上升了，但是其他指标都有一定程度下降，想问下您实验过程中有遇到这种问题吗，我需要调相应的参数吗？

**Comment by xmu-xiaoma666** [comment]
BLUE值确实也可能会有下降，可以尝试将reward值改为0.8*CIDEr+0.2*BLEU4，情况可能会有所缓解。

**Comment by hzf-hhh** [comment]
> BLUE值确实也可能会有下降，可以尝试将reward值改为0.8_CIDEr+0.2_BLEU4，情况可能会有所缓解。

感谢您的回复，还有一个问题：

我注意到代码中强化学习中计算cider的方式好像与最后测试指标的方式有些不同，两种结果不一样，我想问下要加bleu作为奖励值是否需要该写原先的bleu文件，您是否有加了bleu的测试文件可以让我参考一下吗？

    ref_caps_train = list(train_dataset.text)
    cider_train = Cider(PTBTokenizer.tokenize(ref_caps_train))

**Comment by xmu-xiaoma666** [comment]
如果想把BLUE也加入reward，不需要改写bleu文件，只需要计算出CIDEr和BLEU后，将CIDEr和BLEU的加权和作为reward即可。

**Comment by hzf-hhh** [comment]
> 如果想把BLUE也加入reward，不需要改写bleu文件，只需要计算出CIDEr和BLEU后，将CIDEr和BLEU的加权和作为reward即可。

嗯，我知道您的意思，我的问题其实是我看到强化学习中的计算cider的方式是初始化了一个：cider_train
ref_caps_train = list(train_dataset.text)
cider_train = Cider(PTBTokenizer.tokenize(ref_caps_train));
与直接利用cider()(没有传入参数)来计算两种结果有所不同，你知道这两种方式的区别吗

**Comment by xmu-xiaoma666** [comment]
这部分的初始化，我是follow了[meshed-memory-transformer](https://github.com/aimagelab/meshed-memory-transformer)的设置。

**Comment by hzf-hhh** [comment]
> 这部分的初始化，我是follow了[meshed-memory-transformer](https://github.com/aimagelab/meshed-memory-transformer)的设置。

好的，感谢您的解答！祝您生活愉快！
